# Generated by Django 4.2.23 on 2025-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_userrole_client_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='allowed_apps',
            field=models.JSONField(blank=True, default=list, help_text='Apps the user is permitted to access'),
        ),
    ]
