# Generated by Django 4.2.25 on 2025-10-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App name', max_length=150, unique=True)),
                ('slug', models.CharField(help_text='URL-friendly identifier', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='App description')),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
                'db_table': 'usecase',
                'ordering': ['name'],
            },
        ),
    ]
