# Generated by Django 4.2.25 on 2025-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module IDs for this app'),
        ),
    ]
