# Generated by Django 4.2.25 on 2025-10-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0002_usecase_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='atoms_in_molecules',
            field=models.JSONField(blank=True, default=list, help_text='Flattened list of all atoms from selected molecules'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='molecule_atoms',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of molecule IDs to their details and atoms'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='molecules',
            field=models.JSONField(blank=True, default=list, help_text='List of molecule IDs available for this use case'),
        ),
    ]
