# Generated by Django 4.2.25 on 2025-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0003_usecase_atoms_in_molecules_usecase_molecule_atoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='molecule_atoms',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of molecule details with their atoms'),
        ),
    ]
