# Generated by Django 4.2.25 on 2025-10-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0004_alter_usecase_molecule_atoms'),
    ]

    operations = [
    ]
