# Generated by Django 4.2.25 on 2025-10-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0007_usecase_molecules_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='feature_based',
        ),
    ]
