# Generated by Django 4.2.25 on 2025-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
        ('usecase', '0008_remove_usecase_feature_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='molecule_objects',
            field=models.ManyToManyField(blank=True, help_text='Molecules available for this use case', related_name='usecases', to='molecules.molecule'),
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='molecules',
        ),
        migrations.AddField(
            model_name='usecase',
            name='molecules',
            field=models.JSONField(blank=True, default=list, help_text='List of molecule IDs for this use case'),
        ),
    ]
