# Generated by Django 4.2.25 on 2025-10-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0022_app_custom_config_app_is_enabled_app_usecase_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_id', models.CharField(help_text='Custom molecule identifier', max_length=100)),
                ('name', models.CharField(help_text='Molecule name/title', max_length=150)),
                ('type', models.CharField(help_text='Molecule type', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Molecule subtitle/description', max_length=255)),
                ('tag', models.CharField(blank=True, help_text='Category tag for the molecule', max_length=100)),
                ('atoms', models.JSONField(blank=True, default=list, help_text='List of atom IDs in this molecule')),
                ('atom_order', models.JSONField(blank=True, default=list, help_text='Order of atoms in this molecule')),
                ('selected_atoms', models.JSONField(blank=True, default=dict, help_text='Selected atoms configuration')),
                ('connections', models.JSONField(blank=True, default=list, help_text='Molecule connections')),
                ('position', models.JSONField(blank=True, default=dict, help_text='Position data (x, y coordinates)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_molecules', to='registry.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_molecules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Molecule',
                'verbose_name_plural': 'Custom Molecules',
                'db_table': 'custom_molecules',
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'molecule_id')},
            },
        ),
    ]
