# Generated by Django 4.2.25 on 2025-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_molecules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommolecule',
            name='type',
            field=models.CharField(blank=True, default='custom', help_text='Molecule type', max_length=150),
        ),
    ]
