name: trinity-dev

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trinity_db
      POSTGRES_USER: trinity_user
      POSTGRES_PASSWORD: trinity_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - trinity-dev-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - trinity-dev-net

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - trinity-dev-net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio_data:/data
    networks:
      - trinity-dev-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - trinity-dev-net

  web:
    build: ./TrinityBackendDjango
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./TrinityBackendDjango:/code
    env_file:
      - ./TrinityBackendDjango/.env
    ports:
      - "8003:8000"
    environment:
      HOST_IP: ${HOST_IP:-192.168.1.98}
      FRONTEND_PORT: "8081"
      CORS_ALLOWED_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-192.168.1.98}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity-dev.quantmatrixai.com"
      CSRF_TRUSTED_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-192.168.1.98}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity-dev.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
      - flight
    networks:
      - trinity-dev-net
    labels:
      - "environment=dev"
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.routers.django.middlewares=django-strip@docker"
      - "traefik.http.middlewares.django-strip.stripprefix.prefixes=/admin"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  celery:
    build: ./TrinityBackendDjango
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - ./TrinityBackendDjango:/code
    env_file:
      - ./TrinityBackendDjango/.env
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - trinity-dev-net
    environment:
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"

  fastapi:
    build: ./TrinityBackendDjango
    command: uvicorn apps.orchestration.fastapi_app:app --host 0.0.0.0 --port 8001
    volumes:
      - ./TrinityBackendDjango:/code
      - ./TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      FLIGHT_HOST: flight
      FLIGHT_PORT: 8816
      HOST_IP: ${HOST_IP:-192.168.1.98}
      FASTAPI_CORS_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-192.168.1.98}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity-dev.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"
    ports:
      - "8004:8001"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
      - flight
    networks:
      - trinity-dev-net
    labels:
      - "environment=dev"
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8001"

  flight:
    build:
      context: ./TrinityBackendFastAPI
      dockerfile: Dockerfile
    command: python app/flight_server.py
    env_file:
      - ./TrinityBackendDjango/.env
    labels:
      - "environment=dev"
    environment:
      FLIGHT_PORT: 8816
    ports:
      - "8816:8816"
    networks:
      - trinity-dev-net

  trinity-ai:
    build:
      context: ./TrinityAI
      dockerfile: Dockerfile
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      OLLAMA_IP: 10.2.1.65
    ports:
      - "8005:8002"
    networks:
      - trinity-dev-net
    labels:
      - "environment=dev"
      - "traefik.enable=true"
      - "traefik.http.routers.trinity-ai.rule=Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/chat`)"
      - "traefik.http.routers.trinity-ai.entrypoints=web"
      - "traefik.http.routers.trinity-ai.priority=100"
      - "traefik.http.services.trinity-ai.loadbalancer.server.port=8002"

  frontend:
    build:
      context: ./TrinityFrontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - trinity-dev-net
    depends_on:
      - web
    labels:
      - "environment=dev"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`trinity-dev.quantmatrixai.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --providers.docker.constraints=Label(`environment`,`dev`)
    ports:
      - "9081:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - trinity-dev-net
    depends_on:
      - web
      - fastapi
volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:

networks:
  trinity-dev-net:
    name: trinity-dev-net
