services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trinity_db
      POSTGRES_USER: trinity_user
      POSTGRES_PASSWORD: trinity_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    networks:
      - trinity-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - trinity-net

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - trinity-net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio_data:/data
    networks:
      - trinity-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - "80"
    depends_on:
      - postgres
    networks:
      - trinity-net

  web:
    build: ./TrinityBackendDjango
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./TrinityBackendDjango:/code
    env_file:
      - ./TrinityBackendDjango/.env
    expose:
      - "8000"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    networks:
      - trinity-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.routers.django.middlewares=django-strip@docker"
      - "traefik.http.middlewares.django-strip.stripprefix.prefixes=/admin"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  celery:
    build: ./TrinityBackendDjango
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - ./TrinityBackendDjango:/code
    env_file:
      - ./TrinityBackendDjango/.env
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - trinity-net

  fastapi:
    build: ./TrinityBackendDjango
    command: uvicorn apps.orchestration.fastapi_app:app --host 0.0.0.0 --port 8001
    volumes:
      - ./TrinityBackendDjango:/code
      - ./TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      FLIGHT_HOST: flight
      FLIGHT_PORT: 8815
      FASTAPI_CORS_ORIGINS: ${FASTAPI_CORS_ORIGINS:-http://127.0.0.1:8080,http://10.2.1.242:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com}
    expose:
      - "8001"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    networks:
      - trinity-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8001"

  flight:
    build:
      context: ./TrinityBackendFastAPI
      dockerfile: Dockerfile
    command: python app/flight_server.py
    env_file:
      - ./TrinityBackendDjango/.env
    expose:
      - "8815"
    networks:
      - trinity-net

  trinity-ai:
    build:
      context: ./TrinityAI/Agent_fetch_atom
      dockerfile: Dockerfile
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      OLLAMA_IP: 10.2.1.65
    expose:
      - "8002"
    networks:
      - trinity-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trinity-ai.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/chat`)"
      - "traefik.http.routers.trinity-ai.entrypoints=web"
      - "traefik.http.routers.trinity-ai.priority=100"
      - "traefik.http.services.trinity-ai.loadbalancer.server.port=8002"

  frontend:
    build:
      context: ./TrinityFrontend
      dockerfile: Dockerfile
    container_name: trinity-frontend
    expose:
      - "80"
    networks:
      - trinity-net
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`trinity.quantmatrixai.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - trinity-net
    depends_on:
      - web
      - fastapi



volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:

networks:
  trinity-net:
    name: trinity-net
