services:
  postgres:
    ports:
      - "5432:5432"
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
  pgadmin:
    ports:
      - "5050:80"
  web:
    ports:
      - "8000:8000"
    environment:
      FRONTEND_PORT: "8080"
      HOST_IP: ${HOST_IP:-10.2.1.242}
      CORS_ALLOWED_ORIGINS: "http://${HOST_IP:-10.2.1.242}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      CSRF_TRUSTED_ORIGINS: "http://${HOST_IP:-10.2.1.242}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_prod"
  fastapi:
    ports:
      - "8001:8001"
    environment:
      HOST_IP: ${HOST_IP:-10.2.1.242}
      FASTAPI_CORS_ORIGINS: "http://127.0.0.1:8080,http://${HOST_IP:-10.2.1.242}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_prod"
  flight:
    ports:
      - "8815:8815"
  trinity-ai:
    ports:
      - "8002:8002"
  celery:
    environment:
      MONGO_URI: "mongodb://mongo:27017/trinity_prod"
  frontend:
    ports:
      - "8080:80"
    build:
      args:
        VITE_BACKEND_ORIGIN: "http://${HOST_IP:-10.2.1.242}:8000"
        VITE_FRONTEND_PORT: "8080"
        VITE_DJANGO_PORT: "8000"
        VITE_FASTAPI_PORT: "8001"
  traefik:
    ports:
      - "9080:80"
