services:
  postgres:
    ports:
      - "5433:5432"
  minio:
    ports:
      - "9002:9000"
      - "9003:9001"
  pgadmin:
    ports:
      - "5051:80"
  web:
    ports:
      - "8003:8000"
    environment:
      FRONTEND_PORT: "8081"
      HOST_IP: ${HOST_IP:-10.2.1.242}
      CORS_ALLOWED_ORIGINS: "http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
      CSRF_TRUSTED_ORIGINS: "http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
  fastapi:
    ports:
      - "8004:8001"
    environment:
      HOST_IP: ${HOST_IP:-10.2.1.242}
      FASTAPI_CORS_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
  flight:
    ports:
      - "8816:8815"
  trinity-ai:
    ports:
      - "8005:8002"
  frontend:
    ports:
      - "8081:80"
    build:
      args:
        VITE_BACKEND_ORIGIN: "http://${HOST_IP:-10.2.1.242}:8003"
        VITE_FRONTEND_PORT: "8081"
        VITE_DJANGO_PORT: "8003"
        VITE_FASTAPI_PORT: "8004"
  traefik:
    ports:
      - "9081:80"
