services:
  postgres:
    ports:
      - "5433:5432"
  minio:
    ports:
      - "9002:9000"
      - "9003:9001"
  pgadmin:
    ports:
      - "5051:80"
  web:
    ports:
      - "8003:8000"
    environment:
      HOST_IP: ${HOST_IP:-10.2.1.242}
      FRONTEND_PORT: "8081"
      CORS_ALLOWED_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
      CSRF_TRUSTED_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"
    labels:
      traefik.enable: "true"
      traefik.http.routers.django.rule: "Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/admin`)"
      traefik.http.routers.django.entrypoints: "web"
      traefik.http.routers.django.middlewares: "django-strip@docker"
      traefik.http.middlewares.django-strip.stripprefix.prefixes: "/admin"
      traefik.http.services.django.loadbalancer.server.port: "8000"
  fastapi:
    ports:
      - "8004:8001"
    environment:
      HOST_IP: ${HOST_IP:-10.2.1.242}
      FASTAPI_CORS_ORIGINS: "http://127.0.0.1:8081,http://${HOST_IP:-10.2.1.242}:8081,http://172.17.48.1:8081,http://10.2.1.65:8081,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"
    labels:
      traefik.enable: "true"
      traefik.http.routers.fastapi.rule: "Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/api`)"
      traefik.http.routers.fastapi.entrypoints: "web"
      traefik.http.services.fastapi.loadbalancer.server.port: "8001"
  flight:
    ports:
      - "8816:8815"
  trinity-ai:
    ports:
      - "8005:8002"
    labels:
      traefik.enable: "true"
      traefik.http.routers.trinity-ai.rule: "Host(`trinity-dev.quantmatrixai.com`) && PathPrefix(`/chat`)"
      traefik.http.routers.trinity-ai.entrypoints: "web"
      traefik.http.routers.trinity-ai.priority: "100"
      traefik.http.services.trinity-ai.loadbalancer.server.port: "8002"
  celery:
    environment:
      MONGO_URI: "mongodb://mongo:27017/trinity_dev"
  frontend:
    ports:
      - "8081:80"
    build:
      args:
        VITE_BACKEND_ORIGIN: "http://${HOST_IP:-10.2.1.242}:8003"
        VITE_FRONTEND_PORT: "8081"
        VITE_DJANGO_PORT: "8003"
        VITE_FASTAPI_PORT: "8004"
        VITE_HOST_IP: "${HOST_IP:-10.2.1.242}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: "Host(`trinity-dev.quantmatrixai.com`)"
      traefik.http.routers.frontend.entrypoints: "web"
      traefik.http.services.frontend.loadbalancer.server.port: "80"
  traefik:
    ports:
      - "9081:80"
