name: trinity-prod

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trinity_db
      POSTGRES_USER: trinity_user
      POSTGRES_PASSWORD: trinity_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - trinity-net

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - trinity-net

  mongo_admin:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - trinity-net

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - trinity-net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - trinity-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trinity-net

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    networks:
      - trinity-net

  web:
    build: ./TrinityBackendDjango
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./TrinityBackendDjango:/code
      - ./TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - ./TrinityBackendDjango/.env
    ports:
      - "8000:8000"
    environment:
      HOST_IP: ${HOST_IP:-172.22.64.1}
      FRONTEND_PORT: "8080"
      CORS_ALLOWED_ORIGINS: "http://127.0.0.1:8080,http://${HOST_IP:-172.22.64.1}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      CSRF_TRUSTED_ORIGINS: "http://127.0.0.1:8080,http://${HOST_IP:-172.22.64.1}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://root:rootpass@mongo:27017/trinity_prod?authSource=admin"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
      - flight
    networks:
      - trinity-net
    labels:
      - "environment=prod"
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.routers.django.middlewares=django-strip@docker"
      - "traefik.http.middlewares.django-strip.stripprefix.prefixes=/admin"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  celery:
    build: ./TrinityBackendDjango
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - ./TrinityBackendDjango:/code
      - ./TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - ./TrinityBackendDjango/.env
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - trinity-net
    environment:
      MONGO_URI: "mongodb://root:rootpass@mongo:27017/trinity_prod?authSource=admin"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

  fastapi:
    build: ./TrinityBackendDjango
    command: uvicorn apps.orchestration.fastapi_app:app --host 0.0.0.0 --port 8001
    volumes:
      - ./TrinityBackendDjango:/code
      - ./TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      FLIGHT_HOST: flight
      FLIGHT_PORT: 8815
      HOST_IP: ${HOST_IP:-172.22.64.1}
      FASTAPI_CORS_ORIGINS: "http://127.0.0.1:8080,http://${HOST_IP:-172.22.64.1}:8080,http://172.17.48.1:8080,http://10.2.1.65:8080,https://trinity.quantmatrixai.com"
      MONGO_URI: "mongodb://root:rootpass@mongo:27017/trinity_prod?authSource=admin"
      CLASSIFY_MONGO_URI: "mongodb://root:rootpass@mongo:27017/?authSource=admin"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
      - flight
    networks:
      - trinity-net
    labels:
      - "environment=prod"
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8001"

  flight:
    build:
      context: ./TrinityBackendFastAPI
      dockerfile: Dockerfile
    command: python app/flight_server.py
    env_file:
      - ./TrinityBackendDjango/.env
    labels:
      - "environment=prod"
    ports:
      - "8815:8815"
    networks:
      - trinity-net

  trinity-ai:
    build:
      context: ./TrinityAI
      dockerfile: Dockerfile
    env_file:
      - ./TrinityBackendDjango/.env
    environment:
      OLLAMA_IP: 10.2.1.65
    volumes:
      - ./TrinityBackendFastAPI/app/DataStorageRetrieval:/app/DataStorageRetrieval:ro
    ports:
      - "8002:8002"
    networks:
      - trinity-net
    labels:
      - "environment=prod"
      - "traefik.enable=true"
      - "traefik.http.routers.trinity-ai.rule=Host(`trinity.quantmatrixai.com`) && PathPrefix(`/trinityai`)"
      - "traefik.http.routers.trinity-ai.entrypoints=web"
      - "traefik.http.routers.trinity-ai.priority=100"
      - "traefik.http.services.trinity-ai.loadbalancer.server.port=8002"

  frontend:
    build:
      context: ./TrinityFrontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - trinity-net
    depends_on:
      - web
    labels:
      - "environment=prod"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`trinity.quantmatrixai.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --providers.docker.constraints=Label(`environment`,`prod`)
    ports:
      - "9080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - trinity-net
    depends_on:
      - web
      - fastapi



volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:

networks:
  trinity-net:
    name: trinity-net
