"""
Direct test of the file-preview logic without requiring server restart.
Tests the actual code changes we made.
"""
import sys
import os
import io
import pandas as pd

# Add paths
sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from app.features.data_upload_validate.file_ingestion.processors.description_separator import DescriptionSeparator
from app.features.data_upload_validate.file_ingestion.processors.header_detector import HeaderDetector

def test_file_preview_logic():
    """Test the file preview logic directly."""
    
    print("=" * 80)
    print("Testing File Preview Logic (Direct Code Test)")
    print("=" * 80)
    
    # Create test CSV content with description rows
    csv_content = """Report Date:,2024-01-01
Generated By:,Test System
Department:,Engineering
,
Name,Age,City,Salary
John,25,NYC,50000
Jane,30,LA,60000
Bob,35,Chicago,55000
Alice,28,Seattle,58000
Tom,32,Boston,62000
"""
    
    print("\n1. Reading CSV file...")
    df = pd.read_csv(io.StringIO(csv_content), header=None, low_memory=False)
    print(f"   Total rows: {len(df)}")
    print(f"   Total columns: {len(df.columns)}")
    print(f"   First few rows:")
    for i in range(min(5, len(df))):
        print(f"     Row {i}: {df.iloc[i].tolist()}")
    
    print("\n2. Separating description rows from data rows...")
    description_rows, df_data = DescriptionSeparator.separate_description_rows(df)
    print(f"   Description rows: {len(description_rows)}")
    print(f"   Data rows: {len(df_data)}")
    
    if description_rows:
        print(f"   Description rows content:")
        for idx, row in enumerate(description_rows):
            print(f"     Row {idx}: {row}")
    
    print(f"\n   Data rows preview:")
    for i in range(min(3, len(df_data))):
        print(f"     Row {i}: {df_data.iloc[i].tolist()}")
    
    print("\n3. Detecting header row...")
    suggested_header_row_relative = HeaderDetector.find_header_row(df_data.head(20))
    print(f"   Suggested header row (relative to data): {suggested_header_row_relative}")
    
    # Calculate values as the endpoint does
    data_rows_start = len(description_rows)
    suggested_header_row_absolute = data_rows_start + suggested_header_row_relative
    
    if suggested_header_row_relative == 0:
        suggested_header_confidence = "high"
    elif suggested_header_row_relative < 3:
        suggested_header_confidence = "medium"
    else:
        suggested_header_confidence = "low"
    
    print(f"   Data rows start at index: {data_rows_start}")
    print(f"   Suggested header row (absolute): {suggested_header_row_absolute}")
    print(f"   Confidence: {suggested_header_confidence}")
    
    print("\n4. Building response structure (as endpoint does)...")
    
    # Get preview rows (first 15 rows of data)
    preview_rows = df_data.head(15).values.tolist()
    preview_row_count = len(preview_rows)
    
    # Convert description rows to structured format
    description_rows_structured = []
    for idx, row in enumerate(description_rows):
        description_rows_structured.append({
            "row_index": idx + 1,  # 1-indexed for display
            "cells": [str(val) if pd.notna(val) else "" for val in row]
        })
    
    # Convert data rows to structured format
    data_rows_structured = []
    for idx, row in enumerate(preview_rows):
        data_rows_structured.append({
            "row_index": data_rows_start + idx + 1,  # 1-indexed absolute row number
            "relative_index": idx,  # 0-indexed relative to data rows
            "cells": [str(val) if pd.notna(val) else "" for val in row]
        })
    
    column_count = len(df_data.columns) if not df_data.empty else 0
    
    # Build response
    response = {
        "data_rows": data_rows_structured,
        "description_rows": description_rows_structured,
        "data_rows_count": len(df_data),
        "description_rows_count": len(description_rows),
        "data_rows_start": data_rows_start,
        "preview_row_count": preview_row_count,
        "column_count": column_count,
        "total_rows": len(df_data),
        "suggested_header_row": suggested_header_row_relative,
        "suggested_header_row_absolute": suggested_header_row_absolute,
        "suggested_header_confidence": suggested_header_confidence,
        "has_description_rows": len(description_rows) > 0,
    }
    
    print("\n5. Response structure:")
    import json
    print(json.dumps(response, indent=2))
    
    print("\n6. Validation:")
    
    # Validate structure
    required_fields = [
        'data_rows', 'description_rows', 'data_rows_count', 'description_rows_count',
        'data_rows_start', 'preview_row_count', 'column_count', 'total_rows',
        'suggested_header_row', 'suggested_header_row_absolute', 'suggested_header_confidence'
    ]
    
    all_present = all(field in response for field in required_fields)
    print(f"   All required fields present: {all_present}")
    
    if not all_present:
        missing = [f for f in required_fields if f not in response]
        print(f"   Missing fields: {missing}")
        return False
    
    # Validate data_rows structure
    if len(response['data_rows']) == 0:
        print("   [ERROR] data_rows is empty!")
        return False
    
    for idx, row in enumerate(response['data_rows']):
        if 'row_index' not in row or 'relative_index' not in row or 'cells' not in row:
            print(f"   [ERROR] data_row[{idx}] missing required fields")
            return False
    
    print(f"   [OK] data_rows structure valid ({len(response['data_rows'])} rows)")
    
    # Validate description_rows structure
    for idx, row in enumerate(response['description_rows']):
        if 'row_index' not in row or 'cells' not in row:
            print(f"   [ERROR] description_row[{idx}] missing required fields")
            return False
    
    print(f"   [OK] description_rows structure valid ({len(response['description_rows'])} rows)")
    
    print("\n" + "=" * 80)
    print("TEST RESULTS")
    print("=" * 80)
    print(f"[OK] Description rows: {response['description_rows_count']}")
    print(f"[OK] Data rows: {response['data_rows_count']}")
    print(f"[OK] Preview rows returned: {response['preview_row_count']}")
    print(f"[OK] Data rows start at: {response['data_rows_start']}")
    print(f"[OK] Suggested header (relative): {response['suggested_header_row']}")
    print(f"[OK] Suggested header (absolute): {response['suggested_header_row_absolute']}")
    print(f"[OK] Confidence: {response['suggested_header_confidence']}")
    print(f"[OK] Column count: {response['column_count']}")
    print("\n[OK] CODE LOGIC TEST PASSED!")
    print("\nNOTE: The backend server needs to be RESTARTED for these changes to take effect.")
    print("=" * 80)
    
    return True

if __name__ == "__main__":
    success = test_file_preview_logic()
    sys.exit(0 if success else 1)

