{{- if .Values.postgres.enabled }}
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
        imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: {{ .Values.resources.postgres.requests.memory }}
            cpu: {{ .Values.resources.postgres.requests.cpu }}
          limits:
            memory: {{ .Values.resources.postgres.limits.memory }}
            cpu: {{ .Values.resources.postgres.limits.cpu }}
        {{- if .Values.healthChecks.enabled }}
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.username }}
            - -d
            - {{ .Values.postgres.database }}
          initialDelaySeconds: {{ .Values.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.username }}
            - -d
            - {{ .Values.postgres.database }}
          initialDelaySeconds: {{ .Values.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        {{- end }}
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
    name: postgres
  selector:
    app: postgres
---
# PostgreSQL NodePort Service for external access
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    nodePort: 30432  # localhost:30432 -> postgres:5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
{{- end }}