{{- if .Values.redis.enabled }}
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}
        imagePullPolicy: {{ .Values.images.redis.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: {{ .Values.resources.redis.requests.memory }}
            cpu: {{ .Values.resources.redis.requests.cpu }}
          limits:
            memory: {{ .Values.resources.redis.limits.memory }}
            cpu: {{ .Values.resources.redis.limits.cpu }}
        {{- if .Values.healthChecks.enabled }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: {{ .Values.healthChecks.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthChecks.periodSeconds }}
          timeoutSeconds: {{ .Values.healthChecks.timeoutSeconds }}
          failureThreshold: {{ .Values.healthChecks.failureThreshold }}
        {{- end }}
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    protocol: TCP
    name: redis
  selector:
    app: redis
---
# Redis NodePort Service for external access
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    app.kubernetes.io/name: trinity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    nodePort: 30379  # localhost:30379 -> redis:6379
    protocol: TCP
    name: redis
  selector:
    app: redis
{{- end }}