# Generated by Django 4.2.25 on 2025-10-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity_v1_atoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trinityv1atom',
            name='color',
            field=models.CharField(blank=True, help_text="Color associated with the atom's category", max_length=50),
        ),
        migrations.AddField(
            model_name='trinityv1atom',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for the atom'),
        ),
    ]
