# Generated by Django 4.2.23 on 2025-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_project_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="state",
            field=models.JSONField(
                blank=True,
                help_text="Persisted workflow/laboratory configuration for this project.",
                null=True,
            ),
        ),
    ]
