# Generated by Codex on 2025-07-03
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0005_historicallaboratoryaction_laboratoryaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrowDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("atom_id", models.CharField(max_length=150)),
                ("file_key", models.CharField(max_length=150)),
                ("arrow_object", models.CharField(max_length=200)),
                ("flight_path", models.CharField(max_length=200)),
                ("original_csv", models.CharField(max_length=200)),
                ("descriptor", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
