# Generated by Django 4.2.23 on 2025-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_registryenvironment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryenvironment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
