# Generated by Django 4.2.24 on 2025-09-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arrowdataset',
            name='unique_project_csv',
        ),
        migrations.AlterUniqueTogether(
            name='arrowdataset',
            unique_together={('project', 'original_csv')},
        ),
    ]
