# Generated by Django 4.2.24 on 2025-09-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_alter_historicalproject_is_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arrowdataset',
            name='unique_project_csv',
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='arrowdataset',
            unique_together={('project', 'original_csv')},
        ),
    ]
