# Generated by Django 4.2.25 on 2025-10-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_remove_arrowdataset_unique_project_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-specific customizations for this app (e.g., custom modules, settings)'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether this app is enabled for this tenant'),
        ),
        migrations.AddField(
            model_name='app',
            name='usecase_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, help_text='ID of the app definition in public.usecase table', null=True),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-specific customizations for this app (e.g., custom modules, settings)'),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether this app is enabled for this tenant'),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='usecase_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, help_text='ID of the app definition in public.usecase table', null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, help_text='App description (synced from public.usecase)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(help_text='App name (synced from public.usecase)', max_length=150),
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(help_text='App slug (synced from public.usecase)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalapp',
            name='description',
            field=models.TextField(blank=True, help_text='App description (synced from public.usecase)'),
        ),
        migrations.AlterField(
            model_name='historicalapp',
            name='name',
            field=models.CharField(help_text='App name (synced from public.usecase)', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalapp',
            name='slug',
            field=models.SlugField(help_text='App slug (synced from public.usecase)', max_length=150),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['usecase_id', 'is_enabled'], name='registry_ap_usecase_f293b6_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['slug'], name='registry_ap_slug_271164_idx'),
        ),
    ]
