# Generated by Django 4.2.26 on 2025-12-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_projectmodificationhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmodificationhistory',
            new_name='registry_pr_user_id_28f5fd_idx',
            old_name='registry_pr_user_id_modified_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmodificationhistory',
            new_name='registry_pr_project_1d798d_idx',
            old_name='registry_pr_project_id_modified_idx',
        ),
    ]
