# Generated by Django 4.2.26 on 2025-12-02 00:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_rename_registry_pr_user_id_modified_idx_registry_pr_user_id_28f5fd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('vector', models.JSONField(blank=True, default=list)),
                ('vector_norm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='registry.retrievaldocument')),
            ],
            options={
                'unique_together': {('document', 'model_name')},
            },
        ),
        migrations.AddIndex(
            model_name='retrievaldocument',
            index=models.Index(fields=['doc_id'], name='registry_retr_doc_id_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievaldocument',
            index=models.Index(fields=['updated_at'], name='registry_retr_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingcache',
            index=models.Index(fields=['model_name'], name='registry_emb_model_idx'),
        ),
    ]
