# Generated by Django 4.2.26 on 2025-12-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_retrievaldocument_embeddingcache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='embeddingcache',
            new_name='registry_em_model_n_e723d8_idx',
            old_name='registry_emb_model_idx',
        ),
        migrations.RenameIndex(
            model_name='retrievaldocument',
            new_name='registry_re_doc_id_b098cd_idx',
            old_name='registry_retr_doc_id_idx',
        ),
        migrations.RenameIndex(
            model_name='retrievaldocument',
            new_name='registry_re_updated_e6218c_idx',
            old_name='registry_retr_updated_idx',
        ),
    ]
