# Generated by Django 4.2.26 on 2025-11-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Last Celery task id that processed this TaskRun",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="execution_profile",
            field=models.CharField(
                choices=[("io", "I/O bound"), ("cpu", "CPU bound")],
                default="io",
                help_text="Scheduling hint for Celery routing",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="tenant_schema",
            field=models.CharField(
                blank=True,
                help_text="Tenant schema that submitted this task run",
                max_length=63,
            ),
        ),
    ]
