# Generated by Django 4.2.26 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Last Celery task id responsible for executing this run",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="retries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="tenant_schema",
            field=models.CharField(
                blank=True,
                help_text="Schema used when dispatching this task run",
                max_length=63,
            ),
        ),
    ]
