# Generated by Django 4.2.25 on 2025-10-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_project_026913_idx',
            old_name='workflows_w_project_1e4b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_user_id_14a43a_idx',
            old_name='workflows_w_user_id_7c8d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_slug_850f71_idx',
            old_name='workflows_w_slug_9f2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_created_115d8b_idx',
            old_name='workflows_w_created_4a3e2c_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='workflows_w_workflo_a8ea79_idx',
            old_name='workflows_w_workflo_a5e1c8_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrun',
            new_name='workflows_w_status_d36201_idx',
            old_name='workflows_w_status_d2f3a1_idx',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='app_name',
            field=models.CharField(blank=True, default='', help_text='Name of the app using this workflow', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='atoms_in_molecules',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of molecules to their atoms: {molecule_id: [atom1, atom2, ...]}'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='dag_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Complete DAG specification with nodes, edges, positions, and metadata'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description of what this workflow does'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='molecules_used',
            field=models.JSONField(blank=True, default=list, help_text='List of molecule IDs/names used in this workflow'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if execution failed'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='result_data',
            field=models.JSONField(blank=True, default=dict, help_text='Execution results and output data'),
        ),
    ]
