# Generated by Django 4.2.25 on 2025-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='atoms',
            field=models.JSONField(blank=True, default=list, help_text='List of atom IDs in this molecule'),
        ),
    ]
