# Generated by Django 4.2.25 on 2025-10-17 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('molecules', '0003_alter_molecule_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Client identifier', max_length=100)),
                ('app_id', models.CharField(help_text='Application identifier', max_length=100)),
                ('project_id', models.CharField(help_text='Project identifier', max_length=100)),
                ('molecule_id', models.CharField(help_text='Unique molecule identifier', max_length=100)),
                ('name', models.CharField(help_text='Molecule name/title', max_length=150)),
                ('type', models.CharField(help_text='Molecule type', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Molecule subtitle/description', max_length=255)),
                ('tag', models.CharField(blank=True, help_text='Category tag for the molecule', max_length=100)),
                ('atoms', models.JSONField(default=list, help_text='List of atom IDs in this molecule')),
                ('atom_order', models.JSONField(default=list, help_text='Order of atoms in the molecule')),
                ('selected_atoms', models.JSONField(default=dict, help_text='Selected atoms configuration')),
                ('connections', models.JSONField(default=list, help_text='Molecule connections')),
                ('position', models.JSONField(default=dict, help_text='Position in workflow canvas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Molecule',
                'verbose_name_plural': 'Custom Molecules',
                'db_table': 'custom_molecules',
                'ordering': ['-created_at'],
                'unique_together': {('client_id', 'app_id', 'project_id', 'molecule_id')},
            },
        ),
    ]
