services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trinity_db
      POSTGRES_USER: trinity_user
      POSTGRES_PASSWORD: trinity_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - trinity-net

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - trinity-net

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - trinity-net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - trinity-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trinity-net

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    networks:
      - trinity-net

  celery:
    build: .
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      - trinity-net

  fastapi:
    build: .
    command: uvicorn apps.orchestration.fastapi_app:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/code
      - ../TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    env_file:
      - .env
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    networks:
      - trinity-net

  flight:
    build: .
    command: python -m TrinityBackendFastAPI.app.arrow_flight_server
    volumes:
      - .:/code
      - ../TrinityBackendFastAPI:/code/TrinityBackendFastAPI
    ports:
      - "8815:8815"
    depends_on:
      - redis
      - minio
      - mongo
    networks:
      - trinity-net

  trinity-ai:
    build:
      context: ../TrinityAI/Agent_fetch_atom
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - trinity-net

  frontend:
    build:
      context: ../TrinityFrontend
      dockerfile: Dockerfile
    container_name: trinity-frontend
    ports:
      - "8080:80"
    networks:
      - trinity-net
    depends_on:
      - web

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:

networks:
  trinity-net:
