export const LOGIN_ANIMATION_CURTAIN_DELAY = 1700;
export const LOGIN_ANIMATION_CURTAIN_DURATION = 1400;
export const LOGIN_ANIMATION_EXIT_FADE = 500;
export const LOGIN_ANIMATION_TOTAL_DURATION =
  LOGIN_ANIMATION_CURTAIN_DELAY + LOGIN_ANIMATION_CURTAIN_DURATION + LOGIN_ANIMATION_EXIT_FADE;
