# Generated by Django 5.2.4 on 2025-07-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("app_id", models.CharField(blank=True, max_length=255)),
                ("app_name", models.CharField(blank=True, max_length=255)),
                ("project_id", models.CharField(blank=True, max_length=255)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("value_type", models.CharField(default="string", max_length=50)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_vars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("client_id", "app_id", "project_id", "key")},
            },
        ),
    ]
