# Generated by Django 4.2.23 on 2025-07-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userenvironmentvariable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userenvironmentvariable",
            unique_together={("user", "client_id", "app_id", "project_id", "key")},
        ),
    ]
